In [1]:
import numpy as np

In [2]:
# 1
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [93]:
# 2
a = np.zeros([3, 3], dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
# 3
a = np.random.randint(low=1, high=11, size=(5, 5))
print(a)

[[ 7  2  4  1  6]
 [ 5  5  6  2 10]
 [ 3  5  2  4  3]
 [ 2  6  9  8  7]
 [ 7  5  4  2  6]]


In [32]:
# 4
a = np.random.random([4, 4])
print(a)

[[0.7832386  0.82176459 0.91053038 0.63008322]
 [0.94702786 0.15592189 0.71157689 0.54527883]
 [0.63242745 0.47252125 0.57629341 0.99162681]
 [0.51352473 0.84728097 0.72208418 0.18883671]]


In [87]:
# 5
a = np.random.randint(low=1, high=11, size=(5))
b = np.random.randint(low=1, high=11, size=(5))
print(a)
print(b)
print()
print(a + b)
print(a - b)
print(a * b)

[3 9 9 2 3]
[7 2 7 6 3]

[10 11 16  8  6]
[-4  7  2 -4  0]
[21 18 63 12  9]


In [86]:
# 6
a = np.random.randint(low=1, high=11, size=(7))
b = np.random.randint(low=1, high=11, size=(7))
print(a)
print()
print(b)
print()
c = np.dot(a, b)
print(c)

[6 7 2 1 7 3 7]

[10  4  2  6  2  8  8]

192


In [85]:
# 7
a = np.random.randint(low=1, high=11, size=(2, 2))
b = np.random.randint(low=1, high=11, size=(2, 3))
print(a)
print()
print(b)
print()
c = np.dot(a, b)
print(c)


[[8 3]
 [6 1]]

[[ 6 10  7]
 [ 9  6 10]]

[[75 98 86]
 [45 66 52]]


In [66]:
# 8
a = np.random.randint(low=1, high=11, size=(3, 3))
print(a)
print()
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 8  7  2]
 [ 2  6  5]
 [10  2  1]]

[[-0.02083333 -0.015625    0.11979167]
 [ 0.25       -0.0625     -0.1875    ]
 [-0.29166667  0.28125     0.17708333]]


In [68]:
# 9
a = np.random.random([4, 4])
print(a)
print()
a_T = a.T
print(a_T)

[[0.23006285 0.35826049 0.95317644 0.30673024]
 [0.11240823 0.25376684 0.32971123 0.06848648]
 [0.88963552 0.32072341 0.98192109 0.22643168]
 [0.4203074  0.47759189 0.72330023 0.77890012]]

[[0.23006285 0.11240823 0.88963552 0.4203074 ]
 [0.35826049 0.25376684 0.32072341 0.47759189]
 [0.95317644 0.32971123 0.98192109 0.72330023]
 [0.30673024 0.06848648 0.22643168 0.77890012]]


In [83]:
# 10
a = np.random.randint(low=1, high=11, size=(3,4))
print(a)
print()
b = np.random.randint(low=1, high=11, size=(4))
print(b)
c = np.dot(a, b)
print(c)

[[ 2  7  8  5]
 [10  6  9  6]
 [ 8  2  6  1]]

[5 7 8 1]
[128 170 103]


In [84]:
# 11
a = np.random.random([2, 3])
print(a)
print()
b = np.random.random(3)
print(b)
print()
c = np.dot(a, b)
print(c)

[[0.01662092 0.70206699 0.91489885]
 [0.46999941 0.65194523 0.92674393]]

[0.40612251 0.06472971 0.76286941]

[0.75014307 0.94006217]


In [92]:
# 12
a = np.random.randint(low=1, high=10, size=(2, 2))
print(a)
print()
b = np.random.randint(low=1, high=10, size=(2, 2))
print(b)
print()
c = a * b
print(c)

[[4 4]
 [6 8]]

[[3 4]
 [1 9]]

[[12 16]
 [ 6 72]]


In [94]:
# 13
a = np.random.randint(low=1, high=10, size=(2, 2))
print(a)
print()
b = np.random.randint(low=1, high=10, size=(2, 2))
print(b)
print()
c = np.dot(a, b)
print(c)

[[7 8]
 [4 1]]

[[9 4]
 [4 8]]

[[95 92]
 [40 24]]


In [96]:
# 14
a = np.random.randint(low=1, high=101, size=(5, 5))
print(a)
print()
b = a.sum()
print(b)

[[ 1 96  5 85 99]
 [96  6 80 95 50]
 [52 65 88 36 42]
 [ 2 84 59 46  5]
 [95 62 35 90 74]]

1448


In [97]:
# 15
a = np.random.randint(low=1, high=10, size=(4, 4))
print(a)
print()
b = np.random.randint(low=1, high=10, size=(4, 4))
print(b)
print()
c = a - b
print(c)

[[6 2 2 7]
 [4 6 5 9]
 [7 3 7 2]
 [7 7 2 9]]

[[8 2 3 9]
 [1 5 9 3]
 [5 4 2 9]
 [1 7 6 9]]

[[-2  0 -1 -2]
 [ 3  1 -4  6]
 [ 2 -1  5 -7]
 [ 6  0 -4  0]]


In [106]:
# 16
a = np.random.random([3, 3])
print(a)
print()
b = a.sum(axis=1)
print(b)

[[0.78478104 0.56158306 0.27867692]
 [0.76744937 0.66795892 0.82714339]
 [0.21534732 0.49777639 0.30377559]]

[1.62504102 2.26255168 1.0168993 ]


In [117]:
# 17
a = np.random.randint(1, 5, size=(3, 4)) 
print(a)
print()
b = a * a
print(b)


[[1 4 4 2]
 [2 4 2 4]
 [4 2 3 1]]

[[ 1 16 16  4]
 [ 4 16  4 16]
 [16  4  9  1]]


In [133]:
# 18
a = np.random.randint(1, 51, size=(4)) 
print(a)
print()
result = np.sqrt(a)
print(result)

[14 34  4  4]

[3.74165739 5.83095189 2.         2.        ]
