In [76]:
from os import listdir
from os.path import isfile, join
import numpy as np
import pandas as pd
from pathlib import Path

In [77]:
datapath = Path("data")
activities = listdir(datapath)
activities

['idle', 'running', 'stairs', 'walking']

In [78]:
idle = pd.DataFrame()
files = listdir(join(datapath, 'idle'))
for datafile in files:
    file_inf = pd.read_csv(join(join(datapath, 'idle'), datafile))
    idle = pd.concat([idle, file_inf], ignore_index=True)
    
running = pd.DataFrame()
files = listdir(join(datapath, 'running'))
for datafile in files:
    file_inf = pd.read_csv(join(join(datapath, 'running'), datafile))
    running = pd.concat([running, file_inf], ignore_index=True)

stairs = pd.DataFrame()
files = listdir(join(datapath, 'stairs'))
for datafile in files:
    file_inf = pd.read_csv(join(join(datapath, 'stairs'), datafile))
    stairs = pd.concat([stairs, file_inf], ignore_index=True)

walking = pd.DataFrame()
files = listdir(join(datapath, 'walking'))
for datafile in files:
    file_inf = pd.read_csv(join(join(datapath, 'walking'), datafile))
    walking = pd.concat([walking, file_inf], ignore_index=True)

print(idle.head(5))
print(running.head(5))
print(stairs.head(5))
print(walking.head(5))

   accelerometer_X  accelerometer_Y  accelerometer_Z
0         1.000776         4.616021         8.576031
1         0.718261         4.209007         8.446744
2        -0.909797        -0.282516         9.203311
3         5.099650         0.148441         8.418014
4         1.762132        -0.162806         9.251195
   accelerometer_X  accelerometer_Y  accelerometer_Z
0        -4.151545         1.781286         2.173935
1         2.020706         3.706224         9.921572
2         1.762132         4.242526         8.078037
3        -0.445322        11.080365         6.756438
4         5.573702        13.436260        15.054740
   accelerometer_X  accelerometer_Y  accelerometer_Z
0         6.727707         2.973599         3.936068
1         7.891289         0.440533        -3.342306
2         6.301539        -1.154005         0.067038
3         4.534618        -5.755661        -1.369483
4         4.563349        -3.730166        -0.028730
   accelerometer_X  accelerometer_Y  accelerom

In [79]:
idle['activity'] = 0
running['activity'] = 1
stairs['activity'] = 2
walking['activity'] = 3

print(idle.head(5))
print(running.head(5))
print(stairs.head(5))
print(walking.head(5))

   accelerometer_X  accelerometer_Y  accelerometer_Z  activity
0         1.000776         4.616021         8.576031         0
1         0.718261         4.209007         8.446744         0
2        -0.909797        -0.282516         9.203311         0
3         5.099650         0.148441         8.418014         0
4         1.762132        -0.162806         9.251195         0
   accelerometer_X  accelerometer_Y  accelerometer_Z  activity
0        -4.151545         1.781286         2.173935         1
1         2.020706         3.706224         9.921572         1
2         1.762132         4.242526         8.078037         1
3        -0.445322        11.080365         6.756438         1
4         5.573702        13.436260        15.054740         1
   accelerometer_X  accelerometer_Y  accelerometer_Z  activity
0         6.727707         2.973599         3.936068         2
1         7.891289         0.440533        -3.342306         2
2         6.301539        -1.154005         0.067038   

In [80]:
main_df = pd.concat([idle, running, stairs, walking], ignore_index=True)
main_df

accelerometer_X  accelerometer_Y  accelerometer_Z  activity
0              1.000776         4.616021         8.576031         0
1              0.718261         4.209007         8.446744         0
2             -0.909797        -0.282516         9.203311         0
3              5.099650         0.148441         8.418014         0
4              1.762132        -0.162806         9.251195         0
...                 ...              ...              ...       ...
193855         5.109226       -15.452178        -1.470040         3
193856         6.373365       -11.741165        -8.226476         3
193857         3.289633        -9.993398        -0.383072         3
193858        -2.978387        -3.050213         1.273715         3
193859        -4.347870        -9.926360        -1.642422         3

[193860 rows x 4 columns]

In [81]:
y = main_df.activity
X = main_df[['accelerometer_X', 'accelerometer_Y', 'accelerometer_Z']]

In [82]:
features = pd.DataFrame()
features["mean"] = X.mean(axis=1, numeric_only=True)
features["max"] = X.max(axis=1, numeric_only=True)
features["min"] = X.min(axis=1, numeric_only=True)
features["std"] = X.std(axis=1, numeric_only=True)
features["skew"] = X.skew(axis=1, numeric_only=True)
features["median"] = X.median(axis=1, numeric_only=True)
features

mean       max        min        std      skew    median
0       4.730943  8.576031   1.000776   3.788935  0.136363  4.616021
1       4.458004  8.446744   0.718261   3.870253  0.288314  4.209007
2       2.670333  9.203311  -0.909797   5.666412  1.708202 -0.282516
3       4.555368  8.418014   0.148441   4.161567 -0.578477  5.099650
4       3.616840  9.251195  -0.162806   4.973511  1.444755  1.762132
...          ...       ...        ...        ...       ...       ...
193855 -3.937664  5.109226 -15.452178  10.500462 -0.999105 -1.470040
193856 -4.531425  6.373365 -11.741165   9.605941  1.474858 -8.226476
193857 -2.362279  3.289633  -9.993398   6.859131 -1.190365 -0.383072
193858 -1.584962  1.273715  -3.050213   2.475947  1.730411 -2.978387
193859 -5.305551 -1.642422  -9.926360   4.224189 -0.967773 -4.347870

[193860 rows x 6 columns]

In [83]:
X = pd.concat([X, features], axis=1)
X

accelerometer_X  accelerometer_Y  accelerometer_Z      mean       max  \
0              1.000776         4.616021         8.576031  4.730943  8.576031   
1              0.718261         4.209007         8.446744  4.458004  8.446744   
2             -0.909797        -0.282516         9.203311  2.670333  9.203311   
3              5.099650         0.148441         8.418014  4.555368  8.418014   
4              1.762132        -0.162806         9.251195  3.616840  9.251195   
...                 ...              ...              ...       ...       ...   
193855         5.109226       -15.452178        -1.470040 -3.937664  5.109226   
193856         6.373365       -11.741165        -8.226476 -4.531425  6.373365   
193857         3.289633        -9.993398        -0.383072 -2.362279  3.289633   
193858        -2.978387        -3.050213         1.273715 -1.584962  1.273715   
193859        -4.347870        -9.926360        -1.642422 -5.305551 -1.642422   

              min        std      skew    median  
0        1.000776   3.788935  0.136363  4.616021  
1        0.718261   3.870253  0.288314  4.209007  
2       -0.909797   5.666412  1.708202 -0.282516  
3        0.148441   4.161567 -0.578477  5.099650  
4       -0.162806   4.973511  1.444755  1.762132  
...           ...        ...       ...       ...  
193855 -15.452178  10.500462 -0.999105 -1.470040  
193856 -11.741165   9.605941  1.474858 -8.226476  
193857  -9.993398   6.859131 -1.190365 -0.383072  
193858  -3.050213   2.475947  1.730411 -2.978387  
193859  -9.926360   4.224189 -0.967773 -4.347870  

[193860 rows x 9 columns]

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [85]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = SVC()
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)

svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_classification_report = classification_report(y_test, svm_predictions)
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)

print("SVM classifier results:")
print("Accuracy:", svm_accuracy)
print("Classification report:")
print(svm_classification_report)
print("Confusion matrix:")
print(svm_confusion_matrix)

SVM classifier results:
Accuracy: 0.892726709996905
Classification report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      7786
           1       0.93      0.91      0.92     25542
           2       1.00      0.00      0.01      1290
           3       0.80      0.90      0.85     13847

    accuracy                           0.89     48465
   macro avg       0.92      0.70      0.69     48465
weighted avg       0.90      0.89      0.88     48465

Confusion matrix:
[[ 7661    99     0    26]
 [  277 23120     0  2145]
 [   12   329     4   945]
 [   38  1328     0 12481]]


In [86]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_classification_report = classification_report(y_test, rf_predictions)
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)

print("Random forest classifier results:")
print("Accuracy:", rf_accuracy)
print("Classification report:")
print(rf_classification_report)
print("Confusion matrix:")
print(rf_confusion_matrix)

Random forest classifier results:
Accuracy: 0.9995666976168369
Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7786
           1       1.00      1.00      1.00     25542
           2       1.00      0.99      1.00      1290
           3       1.00      1.00      1.00     13847

    accuracy                           1.00     48465
   macro avg       1.00      1.00      1.00     48465
weighted avg       1.00      1.00      1.00     48465

Confusion matrix:
[[ 7786     0     0     0]
 [    0 25541     0     1]
 [    4     4  1278     4]
 [    0     8     0 13839]]


За результатами дослідження можна сказати, що с задає краще впорались випадкові дереви. Вони майже безпомилково классифіківули дані.